name = "unity-v3"
compatibility_date = "2024-09-30"
pages_build_output_dir = "./public"

# D1 Database binding for user authentication and orders
[[d1_databases]]
binding = "DB"
database_name = "unity-v3"
database_id = "1235f2c7-7b73-44b7-95c2-b44260e51179"

# R2 Bucket for official product/marketing images (admin-controlled)
[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "sbs-product-images"

# R2 Bucket for user-uploaded seller photos (separate from products)
[[r2_buckets]]
binding = "USER_UPLOADS"
bucket_name = "sbs-user-uploads"

# Environment variables
[vars]
SITE_URL = "https://thesbsofficial.com"
CLOUDFLARE_ACCOUNT_ID = "625959b904a63f24f6bb7ec9b8c1ed7c"
ADMIN_ALLOWLIST_HANDLES = "fredbademosi,thesbsofficial"

# Resend API Key (get from https://resend.com/api-keys)
# Add this as a secret: npx wrangler secret put RESEND_API_KEY
# Format: re_xxxxxxxxx
