name = "unity-v3"
compatibility_date = "2024-09-30"
pages_build_output_dir = "./public"

# D1 Database binding for user authentication and orders
[[d1_databases]]
binding = "DB"
database_name = "unity-v3"
database_id = "1235f2c7-7b73-44b7-95c2-b44260e51179"

# R2 Bucket for official product/marketing images (admin-controlled)
[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "sbs-product-images"

# R2 Bucket for user-uploaded seller photos (separate from products)
[[r2_buckets]]
binding = "USER_UPLOADS"
bucket_name = "sbs-user-uploads"